set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s

set -g mouse

bind -r g display-popup -d '#{pane_current_path}' -w80% -h80% -E lazygit

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# set-option -g status-position top


# set-option -g status-justify "left"
# set-option -g status-fg cyan
# set-option -g status-bg black
#
# set -g pane-active-border-style fg=colour166,bg=default
# set -g window-style fg=colour10,bg=default
# set -g window-active-style fg=colour12,bg=default
# set-option -g history-limit 64096
#
# set-option -g status-style bg=colour235,fg=colour136,default
#
#
# # default window title colors
# set-window-option -g window-status-style fg=colour244,bg=colour234,dim
#
# # active window title colors
# set-window-option -g window-status-current-style fg=colour166,bg=default,bright
#
# # pane border
# set-option -g pane-border-style fg=colour235 #base02
# set-option -g pane-active-border-style fg=colour136,bg=colour235
#
# # message text
# set-option -g message-style bg=colour235,fg=colour166
#
# # pane number display
# set-option -g display-panes-active-colour colour33 #blue
# set-option -g display-panes-colour colour166 #orange
#
# # clock
# set-window-option -g clock-mode-colour colour64 #green
#
# # allow the title bar to adapt to whatever host you connect to
# set -g set-titles on
# set -g set-titles-string "#T"
#

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'nordtheme/tmux'
# set -g @tmux-gruvbox 'dark'

set -sg escape-time 10
# set -g @plugin 'catppuccin/tmux'
# set -g @catppuccin_flavor 'mocha'
# set -g @catppuccin_window_status_style "rounded"
#
# set -g status-right-length 100
# set -g status-left-length 100
# set -g status-left ""
# set -g status-right "#{E:@catppuccin_status_application}"
# set -agF status-right "#{E:@catppuccin_status_cpu}"
# set -ag status-right "#{E:@catppuccin_status_session}"
# set -ag status-right "#{E:@catppuccin_status_uptime}"
# set -agF status-right "#{E:@catppuccin_status_battery}"
#
run '~/.tmux/plugins/tpm/tpm'
