
# general.import = [
#     "~/.config/alacritty/repothemes/themes/rose-pine.toml"

[general]
# import = ["/home/user/.config/alacritty/themes/themes/blood_moon.toml"]
# import = ["/home/user/.config/alacritty/themes/themes/gruber_darker.toml"]
# import = ["/home/user/.config/alacritty/themes/themes/tokyo_night.toml"]
import = ["/home/user/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[colors.primary]
# background = "#000000"

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
# decorations = "None"

# decorations = "Buttonless"

# opacity = 0.65
# blur = true
dynamic_padding = true

[mouse]
hide_when_typing = true

[font]
normal.family = "JetBrainsMono Nerd Font" 
# normal.family = "FiraCode Nerd Font"
# normal.family = "Iosevka Nerd Font"

size = 14

[keyboard]
bindings = [
  { key = "Left",  mods = "Alt",     chars = "\u001bB"   },# Skip word left
  { key = "Right", mods = "Alt",     chars = "\u001bF"   },# Skip word right
  { key = "Left",  mods = "Command", chars = "\u001bOH"  },# jump word start
  { key = "Right", mods = "Command", chars =  "\u001bOF" },# jump word end
  { key = "Back",  mods = "Command", chars = "\u0015"    },# Delete line
  { key = "Back",  mods = "Command", chars = "\u0017"    },# Delete word
]

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

